/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContactEntity,
  ContactsBulkCreateExtractionForWebAppJobRequestEntity,
  ExceptionResponseEntity,
  ExtractContactFromFileRequestBodyDto,
  JobRequestPayloadEntity,
  StartBulkCreateExtractionForWebAppRequestBodyDto,
} from '../models/index';
import {
    ContactEntityFromJSON,
    ContactEntityToJSON,
    ContactsBulkCreateExtractionForWebAppJobRequestEntityFromJSON,
    ContactsBulkCreateExtractionForWebAppJobRequestEntityToJSON,
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    ExtractContactFromFileRequestBodyDtoFromJSON,
    ExtractContactFromFileRequestBodyDtoToJSON,
    JobRequestPayloadEntityFromJSON,
    JobRequestPayloadEntityToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoToJSON,
} from '../models/index';

export interface ExtractContactFromFileRequest {
    extractContactFromFileRequestBodyDto: ExtractContactFromFileRequestBodyDto;
}

export interface ProcessContactsBulkCreateExtractionForWebAppRequest {
    jobRequestPayloadEntity: JobRequestPayloadEntity;
}

export interface StartContactsBulkCreateExtractionForWebAppRequest {
    startBulkCreateExtractionForWebAppRequestBodyDto: StartBulkCreateExtractionForWebAppRequestBodyDto;
}

/**
 * ContactsApi - interface
 * 
 * @export
 * @interface ContactsApiInterface
 */
export interface ContactsApiInterface {
    /**
     * 
     * @summary Extrai os dados de contato a partir do arquivo.
     * @param {ExtractContactFromFileRequestBodyDto} extractContactFromFileRequestBodyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    extractContactFromFileRaw(requestParameters: ExtractContactFromFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactEntity>>;

    /**
     * Extrai os dados de contato a partir do arquivo.
     */
    extractContactFromFile(requestParameters: ExtractContactFromFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactEntity>;

    /**
     * 
     * @summary Processa os dados do arquivo.
     * @param {JobRequestPayloadEntity} jobRequestPayloadEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    processContactsBulkCreateExtractionForWebAppRaw(requestParameters: ProcessContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Processa os dados do arquivo.
     */
    processContactsBulkCreateExtractionForWebApp(requestParameters: ProcessContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Inicia a extração de contatos em massa a partir do web app.
     * @param {StartBulkCreateExtractionForWebAppRequestBodyDto} startBulkCreateExtractionForWebAppRequestBodyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    startContactsBulkCreateExtractionForWebAppRaw(requestParameters: StartContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactsBulkCreateExtractionForWebAppJobRequestEntity>>;

    /**
     * Inicia a extração de contatos em massa a partir do web app.
     */
    startContactsBulkCreateExtractionForWebApp(requestParameters: StartContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactsBulkCreateExtractionForWebAppJobRequestEntity>;

}

/**
 * 
 */
export class ContactsApi extends runtime.BaseAPI implements ContactsApiInterface {

    /**
     * Extrai os dados de contato a partir do arquivo.
     */
    async extractContactFromFileRaw(requestParameters: ExtractContactFromFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactEntity>> {
        if (requestParameters['extractContactFromFileRequestBodyDto'] == null) {
            throw new runtime.RequiredError(
                'extractContactFromFileRequestBodyDto',
                'Required parameter "extractContactFromFileRequestBodyDto" was null or undefined when calling extractContactFromFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/external/contacts/extract-from-file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExtractContactFromFileRequestBodyDtoToJSON(requestParameters['extractContactFromFileRequestBodyDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactEntityFromJSON(jsonValue));
    }

    /**
     * Extrai os dados de contato a partir do arquivo.
     */
    async extractContactFromFile(requestParameters: ExtractContactFromFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactEntity> {
        const response = await this.extractContactFromFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Processa os dados do arquivo.
     */
    async processContactsBulkCreateExtractionForWebAppRaw(requestParameters: ProcessContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['jobRequestPayloadEntity'] == null) {
            throw new runtime.RequiredError(
                'jobRequestPayloadEntity',
                'Required parameter "jobRequestPayloadEntity" was null or undefined when calling processContactsBulkCreateExtractionForWebApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/internal/queues/contacts-bulk-create-extraction-for-web-app`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JobRequestPayloadEntityToJSON(requestParameters['jobRequestPayloadEntity']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Processa os dados do arquivo.
     */
    async processContactsBulkCreateExtractionForWebApp(requestParameters: ProcessContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.processContactsBulkCreateExtractionForWebAppRaw(requestParameters, initOverrides);
    }

    /**
     * Inicia a extração de contatos em massa a partir do web app.
     */
    async startContactsBulkCreateExtractionForWebAppRaw(requestParameters: StartContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactsBulkCreateExtractionForWebAppJobRequestEntity>> {
        if (requestParameters['startBulkCreateExtractionForWebAppRequestBodyDto'] == null) {
            throw new runtime.RequiredError(
                'startBulkCreateExtractionForWebAppRequestBodyDto',
                'Required parameter "startBulkCreateExtractionForWebAppRequestBodyDto" was null or undefined when calling startContactsBulkCreateExtractionForWebApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/external/contacts/bulk-create-extraction-for-web-app/start`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartBulkCreateExtractionForWebAppRequestBodyDtoToJSON(requestParameters['startBulkCreateExtractionForWebAppRequestBodyDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactsBulkCreateExtractionForWebAppJobRequestEntityFromJSON(jsonValue));
    }

    /**
     * Inicia a extração de contatos em massa a partir do web app.
     */
    async startContactsBulkCreateExtractionForWebApp(requestParameters: StartContactsBulkCreateExtractionForWebAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactsBulkCreateExtractionForWebAppJobRequestEntity> {
        const response = await this.startContactsBulkCreateExtractionForWebAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
