/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmailForwardingIntegrationBestSuggestedActionEntity,
  ExceptionResponseEntity,
  GenerateBestSuggestedActionRequestBodyDto,
} from '../models/index';
import {
    EmailForwardingIntegrationBestSuggestedActionEntityFromJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityToJSON,
    ExceptionResponseEntityFromJSON,
    ExceptionResponseEntityToJSON,
    GenerateBestSuggestedActionRequestBodyDtoFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoToJSON,
} from '../models/index';

export interface SystemGenerateBestSuggestedActionRequest {
    generateBestSuggestedActionRequestBodyDto: GenerateBestSuggestedActionRequestBodyDto;
}

/**
 * EmailForwardingIntegrationApi - interface
 * 
 * @export
 * @interface EmailForwardingIntegrationApiInterface
 */
export interface EmailForwardingIntegrationApiInterface {
    /**
     * 
     * @summary Gera a melhor ação sugerida para integração de encaminhamento de email.
     * @param {GenerateBestSuggestedActionRequestBodyDto} generateBestSuggestedActionRequestBodyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailForwardingIntegrationApiInterface
     */
    systemGenerateBestSuggestedActionRaw(requestParameters: SystemGenerateBestSuggestedActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailForwardingIntegrationBestSuggestedActionEntity>>;

    /**
     * Gera a melhor ação sugerida para integração de encaminhamento de email.
     */
    systemGenerateBestSuggestedAction(requestParameters: SystemGenerateBestSuggestedActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailForwardingIntegrationBestSuggestedActionEntity>;

}

/**
 * 
 */
export class EmailForwardingIntegrationApi extends runtime.BaseAPI implements EmailForwardingIntegrationApiInterface {

    /**
     * Gera a melhor ação sugerida para integração de encaminhamento de email.
     */
    async systemGenerateBestSuggestedActionRaw(requestParameters: SystemGenerateBestSuggestedActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailForwardingIntegrationBestSuggestedActionEntity>> {
        if (requestParameters['generateBestSuggestedActionRequestBodyDto'] == null) {
            throw new runtime.RequiredError(
                'generateBestSuggestedActionRequestBodyDto',
                'Required parameter "generateBestSuggestedActionRequestBodyDto" was null or undefined when calling systemGenerateBestSuggestedAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/internal/email-forwarding-integration/best-suggested-action`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateBestSuggestedActionRequestBodyDtoToJSON(requestParameters['generateBestSuggestedActionRequestBodyDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailForwardingIntegrationBestSuggestedActionEntityFromJSON(jsonValue));
    }

    /**
     * Gera a melhor ação sugerida para integração de encaminhamento de email.
     */
    async systemGenerateBestSuggestedAction(requestParameters: SystemGenerateBestSuggestedActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailForwardingIntegrationBestSuggestedActionEntity> {
        const response = await this.systemGenerateBestSuggestedActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
