/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 2.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartBulkCreateExtractionForWebAppRequestBodyDtoFile } from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import {
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped,
} from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import type { AgentRequestBodyDtoMessageContext } from './AgentRequestBodyDtoMessageContext';
import {
    AgentRequestBodyDtoMessageContextFromJSON,
    AgentRequestBodyDtoMessageContextFromJSONTyped,
    AgentRequestBodyDtoMessageContextToJSON,
    AgentRequestBodyDtoMessageContextToJSONTyped,
} from './AgentRequestBodyDtoMessageContext';

/**
 * 
 * @export
 * @interface AgentProcessingRequestBodyDto
 */
export interface AgentProcessingRequestBodyDto {
    /**
     * O ID do usuário principal.
     * @type {string}
     * @memberof AgentProcessingRequestBodyDto
     */
    mainUserId?: string | null;
    /**
     * Os arquivos enviados pelo usuário.
     * @type {Array<StartBulkCreateExtractionForWebAppRequestBodyDtoFile>}
     * @memberof AgentProcessingRequestBodyDto
     */
    files: Array<StartBulkCreateExtractionForWebAppRequestBodyDtoFile>;
    /**
     * 
     * @type {AgentRequestBodyDtoMessageContext}
     * @memberof AgentProcessingRequestBodyDto
     */
    messageContext: AgentRequestBodyDtoMessageContext;
    /**
     * As últimas mensagens enviadas pela Sofia falando que está processando.
     * @type {Array<string>}
     * @memberof AgentProcessingRequestBodyDto
     */
    latestProcessingReplies: Array<string>;
}

/**
 * Check if a given object implements the AgentProcessingRequestBodyDto interface.
 */
export function instanceOfAgentProcessingRequestBodyDto(value: object): value is AgentProcessingRequestBodyDto {
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('messageContext' in value) || value['messageContext'] === undefined) return false;
    if (!('latestProcessingReplies' in value) || value['latestProcessingReplies'] === undefined) return false;
    return true;
}

export function AgentProcessingRequestBodyDtoFromJSON(json: any): AgentProcessingRequestBodyDto {
    return AgentProcessingRequestBodyDtoFromJSONTyped(json, false);
}

export function AgentProcessingRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentProcessingRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mainUserId': json['mainUserId'] == null ? undefined : json['mainUserId'],
        'files': ((json['files'] as Array<any>).map(StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON)),
        'messageContext': AgentRequestBodyDtoMessageContextFromJSON(json['messageContext']),
        'latestProcessingReplies': json['latestProcessingReplies'],
    };
}

export function AgentProcessingRequestBodyDtoToJSON(json: any): AgentProcessingRequestBodyDto {
    return AgentProcessingRequestBodyDtoToJSONTyped(json, false);
}

export function AgentProcessingRequestBodyDtoToJSONTyped(value?: AgentProcessingRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mainUserId': value['mainUserId'],
        'files': ((value['files'] as Array<any>).map(StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON)),
        'messageContext': AgentRequestBodyDtoMessageContextToJSON(value['messageContext']),
        'latestProcessingReplies': value['latestProcessingReplies'],
    };
}

