/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 3.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartBulkCreateExtractionForWebAppRequestBodyDtoFile } from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import {
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped,
} from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import type { AgentRequestBodyDtoMessageContext } from './AgentRequestBodyDtoMessageContext';
import {
    AgentRequestBodyDtoMessageContextFromJSON,
    AgentRequestBodyDtoMessageContextFromJSONTyped,
    AgentRequestBodyDtoMessageContextToJSON,
    AgentRequestBodyDtoMessageContextToJSONTyped,
} from './AgentRequestBodyDtoMessageContext';

/**
 * 
 * @export
 * @interface AgentRequestBodyDto
 */
export interface AgentRequestBodyDto {
    /**
     * O ID do usuário principal.
     * @type {string}
     * @memberof AgentRequestBodyDto
     */
    mainUserId?: string | null;
    /**
     * Os arquivos enviados pelo usuário.
     * @type {Array<StartBulkCreateExtractionForWebAppRequestBodyDtoFile>}
     * @memberof AgentRequestBodyDto
     */
    files: Array<StartBulkCreateExtractionForWebAppRequestBodyDtoFile>;
    /**
     * 
     * @type {AgentRequestBodyDtoMessageContext}
     * @memberof AgentRequestBodyDto
     */
    messageContext: AgentRequestBodyDtoMessageContext;
}

/**
 * Check if a given object implements the AgentRequestBodyDto interface.
 */
export function instanceOfAgentRequestBodyDto(value: object): value is AgentRequestBodyDto {
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('messageContext' in value) || value['messageContext'] === undefined) return false;
    return true;
}

export function AgentRequestBodyDtoFromJSON(json: any): AgentRequestBodyDto {
    return AgentRequestBodyDtoFromJSONTyped(json, false);
}

export function AgentRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mainUserId': json['mainUserId'] == null ? undefined : json['mainUserId'],
        'files': ((json['files'] as Array<any>).map(StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON)),
        'messageContext': AgentRequestBodyDtoMessageContextFromJSON(json['messageContext']),
    };
}

export function AgentRequestBodyDtoToJSON(json: any): AgentRequestBodyDto {
    return AgentRequestBodyDtoToJSONTyped(json, false);
}

export function AgentRequestBodyDtoToJSONTyped(value?: AgentRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mainUserId': value['mainUserId'],
        'files': ((value['files'] as Array<any>).map(StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON)),
        'messageContext': AgentRequestBodyDtoMessageContextToJSON(value['messageContext']),
    };
}

