/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentReplyEntityText
 */
export interface AgentReplyEntityText {
    /**
     * 
     * @type {string}
     * @memberof AgentReplyEntityText
     */
    body: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgentReplyEntityText
     */
    enableLinkPreview?: boolean;
}

/**
 * Check if a given object implements the AgentReplyEntityText interface.
 */
export function instanceOfAgentReplyEntityText(value: object): value is AgentReplyEntityText {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function AgentReplyEntityTextFromJSON(json: any): AgentReplyEntityText {
    return AgentReplyEntityTextFromJSONTyped(json, false);
}

export function AgentReplyEntityTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentReplyEntityText {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'enableLinkPreview': json['enableLinkPreview'] == null ? undefined : json['enableLinkPreview'],
    };
}

export function AgentReplyEntityTextToJSON(json: any): AgentReplyEntityText {
    return AgentReplyEntityTextToJSONTyped(json, false);
}

export function AgentReplyEntityTextToJSONTyped(value?: AgentReplyEntityText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'enableLinkPreview': value['enableLinkPreview'],
    };
}

