/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentReplyEntityDocument
 */
export interface AgentReplyEntityDocument {
    /**
     * 
     * @type {string}
     * @memberof AgentReplyEntityDocument
     */
    signedUrl: string;
    /**
     * 
     * @type {string}
     * @memberof AgentReplyEntityDocument
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof AgentReplyEntityDocument
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof AgentReplyEntityDocument
     */
    caption?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentReplyEntityDocument
     */
    fileSize: number;
}

/**
 * Check if a given object implements the AgentReplyEntityDocument interface.
 */
export function instanceOfAgentReplyEntityDocument(value: object): value is AgentReplyEntityDocument {
    if (!('signedUrl' in value) || value['signedUrl'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    return true;
}

export function AgentReplyEntityDocumentFromJSON(json: any): AgentReplyEntityDocument {
    return AgentReplyEntityDocumentFromJSONTyped(json, false);
}

export function AgentReplyEntityDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentReplyEntityDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'signedUrl': json['signedUrl'],
        'fileName': json['fileName'],
        'mimeType': json['mimeType'],
        'caption': json['caption'] == null ? undefined : json['caption'],
        'fileSize': json['fileSize'],
    };
}

export function AgentReplyEntityDocumentToJSON(json: any): AgentReplyEntityDocument {
    return AgentReplyEntityDocumentToJSONTyped(json, false);
}

export function AgentReplyEntityDocumentToJSONTyped(value?: AgentReplyEntityDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signedUrl': value['signedUrl'],
        'fileName': value['fileName'],
        'mimeType': value['mimeType'],
        'caption': value['caption'],
        'fileSize': value['fileSize'],
    };
}

