/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.8.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentReplyEntityToolCallsInner
 */
export interface AgentReplyEntityToolCallsInner {
    /**
     * 
     * @type {string}
     * @memberof AgentReplyEntityToolCallsInner
     */
    toolCallId: string;
    /**
     * 
     * @type {string}
     * @memberof AgentReplyEntityToolCallsInner
     */
    toolName: string;
    /**
     * 
     * @type {any}
     * @memberof AgentReplyEntityToolCallsInner
     */
    input: any | null;
}

/**
 * Check if a given object implements the AgentReplyEntityToolCallsInner interface.
 */
export function instanceOfAgentReplyEntityToolCallsInner(value: object): value is AgentReplyEntityToolCallsInner {
    if (!('toolCallId' in value) || value['toolCallId'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function AgentReplyEntityToolCallsInnerFromJSON(json: any): AgentReplyEntityToolCallsInner {
    return AgentReplyEntityToolCallsInnerFromJSONTyped(json, false);
}

export function AgentReplyEntityToolCallsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentReplyEntityToolCallsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'toolCallId': json['toolCallId'],
        'toolName': json['toolName'],
        'input': json['input'],
    };
}

export function AgentReplyEntityToolCallsInnerToJSON(json: any): AgentReplyEntityToolCallsInner {
    return AgentReplyEntityToolCallsInnerToJSONTyped(json, false);
}

export function AgentReplyEntityToolCallsInnerToJSONTyped(value?: AgentReplyEntityToolCallsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toolCallId': value['toolCallId'],
        'toolName': value['toolName'],
        'input': value['input'],
    };
}

