/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.8.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage } from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage';
import {
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromJSONTyped,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToJSONTyped,
} from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage';

/**
 * O contexto da conversa da Sofia com o usuário.
 * @export
 * @interface AgentRequestBodyDtoMessageContext
 */
export interface AgentRequestBodyDtoMessageContext {
    /**
     * ID do chat.
     * @type {string}
     * @memberof AgentRequestBodyDtoMessageContext
     */
    chatId: string;
    /**
     * Título do chat.
     * @type {string}
     * @memberof AgentRequestBodyDtoMessageContext
     */
    chatTitle?: string | null;
    /**
     * Canal da mensagem.
     * @type {string}
     * @memberof AgentRequestBodyDtoMessageContext
     */
    channel: AgentRequestBodyDtoMessageContextChannelEnum;
    /**
     * 
     * @type {GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage}
     * @memberof AgentRequestBodyDtoMessageContext
     */
    currentMessage: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage;
    /**
     * 
     * @type {Array<GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage>}
     * @memberof AgentRequestBodyDtoMessageContext
     */
    lastMessages: Array<GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage>;
}


/**
 * @export
 */
export const AgentRequestBodyDtoMessageContextChannelEnum = {
    Whatsapp: 'whatsapp',
    Email: 'email'
} as const;
export type AgentRequestBodyDtoMessageContextChannelEnum = typeof AgentRequestBodyDtoMessageContextChannelEnum[keyof typeof AgentRequestBodyDtoMessageContextChannelEnum];


/**
 * Check if a given object implements the AgentRequestBodyDtoMessageContext interface.
 */
export function instanceOfAgentRequestBodyDtoMessageContext(value: object): value is AgentRequestBodyDtoMessageContext {
    if (!('chatId' in value) || value['chatId'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('currentMessage' in value) || value['currentMessage'] === undefined) return false;
    if (!('lastMessages' in value) || value['lastMessages'] === undefined) return false;
    return true;
}

export function AgentRequestBodyDtoMessageContextFromJSON(json: any): AgentRequestBodyDtoMessageContext {
    return AgentRequestBodyDtoMessageContextFromJSONTyped(json, false);
}

export function AgentRequestBodyDtoMessageContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentRequestBodyDtoMessageContext {
    if (json == null) {
        return json;
    }
    return {
        
        'chatId': json['chatId'],
        'chatTitle': json['chatTitle'] == null ? undefined : json['chatTitle'],
        'channel': json['channel'],
        'currentMessage': GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromJSON(json['currentMessage']),
        'lastMessages': ((json['lastMessages'] as Array<any>).map(GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromJSON)),
    };
}

export function AgentRequestBodyDtoMessageContextToJSON(json: any): AgentRequestBodyDtoMessageContext {
    return AgentRequestBodyDtoMessageContextToJSONTyped(json, false);
}

export function AgentRequestBodyDtoMessageContextToJSONTyped(value?: AgentRequestBodyDtoMessageContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chatId': value['chatId'],
        'chatTitle': value['chatTitle'],
        'channel': value['channel'],
        'currentMessage': GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToJSON(value['currentMessage']),
        'lastMessages': ((value['lastMessages'] as Array<any>).map(GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToJSON)),
    };
}

