/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord } from './BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord';
import {
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordFromJSON,
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordFromJSONTyped,
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordToJSON,
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordToJSONTyped,
} from './BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord';

/**
 * 
 * @export
 * @interface BankTransactionsBestSuggestedActionEntityCreateData
 */
export interface BankTransactionsBestSuggestedActionEntityCreateData {
    /**
     * 
     * @type {BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord}
     * @memberof BankTransactionsBestSuggestedActionEntityCreateData
     */
    financialRecord: BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord;
}

/**
 * Check if a given object implements the BankTransactionsBestSuggestedActionEntityCreateData interface.
 */
export function instanceOfBankTransactionsBestSuggestedActionEntityCreateData(value: object): value is BankTransactionsBestSuggestedActionEntityCreateData {
    if (!('financialRecord' in value) || value['financialRecord'] === undefined) return false;
    return true;
}

export function BankTransactionsBestSuggestedActionEntityCreateDataFromJSON(json: any): BankTransactionsBestSuggestedActionEntityCreateData {
    return BankTransactionsBestSuggestedActionEntityCreateDataFromJSONTyped(json, false);
}

export function BankTransactionsBestSuggestedActionEntityCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransactionsBestSuggestedActionEntityCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'financialRecord': BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordFromJSON(json['financialRecord']),
    };
}

export function BankTransactionsBestSuggestedActionEntityCreateDataToJSON(json: any): BankTransactionsBestSuggestedActionEntityCreateData {
    return BankTransactionsBestSuggestedActionEntityCreateDataToJSONTyped(json, false);
}

export function BankTransactionsBestSuggestedActionEntityCreateDataToJSONTyped(value?: BankTransactionsBestSuggestedActionEntityCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'financialRecord': BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordToJSON(value['financialRecord']),
    };
}

