/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankTransactionsBestSuggestedActionEntityCreateData } from './BankTransactionsBestSuggestedActionEntityCreateData';
import {
    BankTransactionsBestSuggestedActionEntityCreateDataFromJSON,
    BankTransactionsBestSuggestedActionEntityCreateDataFromJSONTyped,
    BankTransactionsBestSuggestedActionEntityCreateDataToJSON,
    BankTransactionsBestSuggestedActionEntityCreateDataToJSONTyped,
} from './BankTransactionsBestSuggestedActionEntityCreateData';
import type { BankTransactionsBestSuggestedActionEntityLinkData } from './BankTransactionsBestSuggestedActionEntityLinkData';
import {
    BankTransactionsBestSuggestedActionEntityLinkDataFromJSON,
    BankTransactionsBestSuggestedActionEntityLinkDataFromJSONTyped,
    BankTransactionsBestSuggestedActionEntityLinkDataToJSON,
    BankTransactionsBestSuggestedActionEntityLinkDataToJSONTyped,
} from './BankTransactionsBestSuggestedActionEntityLinkData';

/**
 * 
 * @export
 * @interface BankTransactionsBestSuggestedActionEntity
 */
export interface BankTransactionsBestSuggestedActionEntity {
    /**
     * 
     * @type {string}
     * @memberof BankTransactionsBestSuggestedActionEntity
     */
    operation: BankTransactionsBestSuggestedActionEntityOperationEnum;
    /**
     * 
     * @type {BankTransactionsBestSuggestedActionEntityLinkData}
     * @memberof BankTransactionsBestSuggestedActionEntity
     */
    linkData?: BankTransactionsBestSuggestedActionEntityLinkData | null;
    /**
     * 
     * @type {BankTransactionsBestSuggestedActionEntityCreateData}
     * @memberof BankTransactionsBestSuggestedActionEntity
     */
    createData: BankTransactionsBestSuggestedActionEntityCreateData;
}


/**
 * @export
 */
export const BankTransactionsBestSuggestedActionEntityOperationEnum = {
    Create: 'CREATE',
    Link: 'LINK'
} as const;
export type BankTransactionsBestSuggestedActionEntityOperationEnum = typeof BankTransactionsBestSuggestedActionEntityOperationEnum[keyof typeof BankTransactionsBestSuggestedActionEntityOperationEnum];


/**
 * Check if a given object implements the BankTransactionsBestSuggestedActionEntity interface.
 */
export function instanceOfBankTransactionsBestSuggestedActionEntity(value: object): value is BankTransactionsBestSuggestedActionEntity {
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('createData' in value) || value['createData'] === undefined) return false;
    return true;
}

export function BankTransactionsBestSuggestedActionEntityFromJSON(json: any): BankTransactionsBestSuggestedActionEntity {
    return BankTransactionsBestSuggestedActionEntityFromJSONTyped(json, false);
}

export function BankTransactionsBestSuggestedActionEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransactionsBestSuggestedActionEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'],
        'linkData': json['linkData'] == null ? undefined : BankTransactionsBestSuggestedActionEntityLinkDataFromJSON(json['linkData']),
        'createData': BankTransactionsBestSuggestedActionEntityCreateDataFromJSON(json['createData']),
    };
}

export function BankTransactionsBestSuggestedActionEntityToJSON(json: any): BankTransactionsBestSuggestedActionEntity {
    return BankTransactionsBestSuggestedActionEntityToJSONTyped(json, false);
}

export function BankTransactionsBestSuggestedActionEntityToJSONTyped(value?: BankTransactionsBestSuggestedActionEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'linkData': BankTransactionsBestSuggestedActionEntityLinkDataToJSON(value['linkData']),
        'createData': BankTransactionsBestSuggestedActionEntityCreateDataToJSON(value['createData']),
    };
}

