/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankTransactionsBestSuggestedActionEntityLinkData
 */
export interface BankTransactionsBestSuggestedActionEntityLinkData {
    /**
     * 
     * @type {string}
     * @memberof BankTransactionsBestSuggestedActionEntityLinkData
     */
    financialRecordId: string;
}

/**
 * Check if a given object implements the BankTransactionsBestSuggestedActionEntityLinkData interface.
 */
export function instanceOfBankTransactionsBestSuggestedActionEntityLinkData(value: object): value is BankTransactionsBestSuggestedActionEntityLinkData {
    if (!('financialRecordId' in value) || value['financialRecordId'] === undefined) return false;
    return true;
}

export function BankTransactionsBestSuggestedActionEntityLinkDataFromJSON(json: any): BankTransactionsBestSuggestedActionEntityLinkData {
    return BankTransactionsBestSuggestedActionEntityLinkDataFromJSONTyped(json, false);
}

export function BankTransactionsBestSuggestedActionEntityLinkDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransactionsBestSuggestedActionEntityLinkData {
    if (json == null) {
        return json;
    }
    return {
        
        'financialRecordId': json['financialRecordId'],
    };
}

export function BankTransactionsBestSuggestedActionEntityLinkDataToJSON(json: any): BankTransactionsBestSuggestedActionEntityLinkData {
    return BankTransactionsBestSuggestedActionEntityLinkDataToJSONTyped(json, false);
}

export function BankTransactionsBestSuggestedActionEntityLinkDataToJSONTyped(value?: BankTransactionsBestSuggestedActionEntityLinkData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'financialRecordId': value['financialRecordId'],
    };
}

