/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Endereço do contato.
 * @export
 * @interface ContactEntityAddress
 */
export interface ContactEntityAddress {
    /**
     * CEP do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    cep?: string | null;
    /**
     * Rua do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    street?: string | null;
    /**
     * Número do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    number?: string | null;
    /**
     * Complemento do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    complement?: string | null;
    /**
     * Bairro do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    neighborhood?: string | null;
    /**
     * Cidade do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    city?: string | null;
    /**
     * Estado do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    state?: string | null;
    /**
     * País do endereço do contato.
     * @type {string}
     * @memberof ContactEntityAddress
     */
    country?: string | null;
}

/**
 * Check if a given object implements the ContactEntityAddress interface.
 */
export function instanceOfContactEntityAddress(value: object): value is ContactEntityAddress {
    return true;
}

export function ContactEntityAddressFromJSON(json: any): ContactEntityAddress {
    return ContactEntityAddressFromJSONTyped(json, false);
}

export function ContactEntityAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactEntityAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'cep': json['cep'] == null ? undefined : json['cep'],
        'street': json['street'] == null ? undefined : json['street'],
        'number': json['number'] == null ? undefined : json['number'],
        'complement': json['complement'] == null ? undefined : json['complement'],
        'neighborhood': json['neighborhood'] == null ? undefined : json['neighborhood'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function ContactEntityAddressToJSON(json: any): ContactEntityAddress {
    return ContactEntityAddressToJSONTyped(json, false);
}

export function ContactEntityAddressToJSONTyped(value?: ContactEntityAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cep': value['cep'],
        'street': value['street'],
        'number': value['number'],
        'complement': value['complement'],
        'neighborhood': value['neighborhood'],
        'city': value['city'],
        'state': value['state'],
        'country': value['country'],
    };
}

