/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartBulkCreateExtractionForWebAppRequestBodyDtoFile } from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import {
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped,
} from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';

/**
 * 
 * @export
 * @interface ContactsBulkCreateExtractionForWebAppJobRequestEntity
 */
export interface ContactsBulkCreateExtractionForWebAppJobRequestEntity {
    /**
     * 
     * @type {string}
     * @memberof ContactsBulkCreateExtractionForWebAppJobRequestEntity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContactsBulkCreateExtractionForWebAppJobRequestEntity
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ContactsBulkCreateExtractionForWebAppJobRequestEntity
     */
    organizationId: string;
    /**
     * 
     * @type {StartBulkCreateExtractionForWebAppRequestBodyDtoFile}
     * @memberof ContactsBulkCreateExtractionForWebAppJobRequestEntity
     */
    file: StartBulkCreateExtractionForWebAppRequestBodyDtoFile;
    /**
     * 
     * @type {string}
     * @memberof ContactsBulkCreateExtractionForWebAppJobRequestEntity
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ContactsBulkCreateExtractionForWebAppJobRequestEntity
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the ContactsBulkCreateExtractionForWebAppJobRequestEntity interface.
 */
export function instanceOfContactsBulkCreateExtractionForWebAppJobRequestEntity(value: object): value is ContactsBulkCreateExtractionForWebAppJobRequestEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ContactsBulkCreateExtractionForWebAppJobRequestEntityFromJSON(json: any): ContactsBulkCreateExtractionForWebAppJobRequestEntity {
    return ContactsBulkCreateExtractionForWebAppJobRequestEntityFromJSONTyped(json, false);
}

export function ContactsBulkCreateExtractionForWebAppJobRequestEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactsBulkCreateExtractionForWebAppJobRequestEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'organizationId': json['organizationId'],
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON(json['file']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function ContactsBulkCreateExtractionForWebAppJobRequestEntityToJSON(json: any): ContactsBulkCreateExtractionForWebAppJobRequestEntity {
    return ContactsBulkCreateExtractionForWebAppJobRequestEntityToJSONTyped(json, false);
}

export function ContactsBulkCreateExtractionForWebAppJobRequestEntityToJSONTyped(value?: ContactsBulkCreateExtractionForWebAppJobRequestEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'organizationId': value['organizationId'],
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON(value['file']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

