/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailForwardingIntegrationBestSuggestedActionEntityCreateManyData } from './EmailForwardingIntegrationBestSuggestedActionEntityCreateManyData';
import {
    EmailForwardingIntegrationBestSuggestedActionEntityCreateManyDataFromJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityCreateManyDataFromJSONTyped,
    EmailForwardingIntegrationBestSuggestedActionEntityCreateManyDataToJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityCreateManyDataToJSONTyped,
} from './EmailForwardingIntegrationBestSuggestedActionEntityCreateManyData';
import type { EmailForwardingIntegrationBestSuggestedActionEntityLinkData } from './EmailForwardingIntegrationBestSuggestedActionEntityLinkData';
import {
    EmailForwardingIntegrationBestSuggestedActionEntityLinkDataFromJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityLinkDataFromJSONTyped,
    EmailForwardingIntegrationBestSuggestedActionEntityLinkDataToJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityLinkDataToJSONTyped,
} from './EmailForwardingIntegrationBestSuggestedActionEntityLinkData';
import type { EmailForwardingIntegrationBestSuggestedActionEntityCreateData } from './EmailForwardingIntegrationBestSuggestedActionEntityCreateData';
import {
    EmailForwardingIntegrationBestSuggestedActionEntityCreateDataFromJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityCreateDataFromJSONTyped,
    EmailForwardingIntegrationBestSuggestedActionEntityCreateDataToJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityCreateDataToJSONTyped,
} from './EmailForwardingIntegrationBestSuggestedActionEntityCreateData';
import type { EmailForwardingIntegrationBestSuggestedActionEntityUpdateData } from './EmailForwardingIntegrationBestSuggestedActionEntityUpdateData';
import {
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataFromJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataFromJSONTyped,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataToJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataToJSONTyped,
} from './EmailForwardingIntegrationBestSuggestedActionEntityUpdateData';

/**
 * 
 * @export
 * @interface EmailForwardingIntegrationBestSuggestedActionEntity
 */
export interface EmailForwardingIntegrationBestSuggestedActionEntity {
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntity
     */
    operation?: EmailForwardingIntegrationBestSuggestedActionEntityOperationEnum | null;
    /**
     * 
     * @type {EmailForwardingIntegrationBestSuggestedActionEntityCreateData}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntity
     */
    createData?: EmailForwardingIntegrationBestSuggestedActionEntityCreateData | null;
    /**
     * 
     * @type {EmailForwardingIntegrationBestSuggestedActionEntityUpdateData}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntity
     */
    updateData?: EmailForwardingIntegrationBestSuggestedActionEntityUpdateData | null;
    /**
     * 
     * @type {EmailForwardingIntegrationBestSuggestedActionEntityCreateManyData}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntity
     */
    createManyData?: EmailForwardingIntegrationBestSuggestedActionEntityCreateManyData | null;
    /**
     * 
     * @type {EmailForwardingIntegrationBestSuggestedActionEntityLinkData}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntity
     */
    linkData?: EmailForwardingIntegrationBestSuggestedActionEntityLinkData | null;
}


/**
 * @export
 */
export const EmailForwardingIntegrationBestSuggestedActionEntityOperationEnum = {
    Create: 'CREATE',
    Update: 'UPDATE',
    CreateMany: 'CREATE_MANY',
    Link: 'LINK'
} as const;
export type EmailForwardingIntegrationBestSuggestedActionEntityOperationEnum = typeof EmailForwardingIntegrationBestSuggestedActionEntityOperationEnum[keyof typeof EmailForwardingIntegrationBestSuggestedActionEntityOperationEnum];


/**
 * Check if a given object implements the EmailForwardingIntegrationBestSuggestedActionEntity interface.
 */
export function instanceOfEmailForwardingIntegrationBestSuggestedActionEntity(value: object): value is EmailForwardingIntegrationBestSuggestedActionEntity {
    return true;
}

export function EmailForwardingIntegrationBestSuggestedActionEntityFromJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntity {
    return EmailForwardingIntegrationBestSuggestedActionEntityFromJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailForwardingIntegrationBestSuggestedActionEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : json['operation'],
        'createData': json['createData'] == null ? undefined : EmailForwardingIntegrationBestSuggestedActionEntityCreateDataFromJSON(json['createData']),
        'updateData': json['updateData'] == null ? undefined : EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataFromJSON(json['updateData']),
        'createManyData': json['createManyData'] == null ? undefined : EmailForwardingIntegrationBestSuggestedActionEntityCreateManyDataFromJSON(json['createManyData']),
        'linkData': json['linkData'] == null ? undefined : EmailForwardingIntegrationBestSuggestedActionEntityLinkDataFromJSON(json['linkData']),
    };
}

export function EmailForwardingIntegrationBestSuggestedActionEntityToJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntity {
    return EmailForwardingIntegrationBestSuggestedActionEntityToJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityToJSONTyped(value?: EmailForwardingIntegrationBestSuggestedActionEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'createData': EmailForwardingIntegrationBestSuggestedActionEntityCreateDataToJSON(value['createData']),
        'updateData': EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataToJSON(value['updateData']),
        'createManyData': EmailForwardingIntegrationBestSuggestedActionEntityCreateManyDataToJSON(value['createManyData']),
        'linkData': EmailForwardingIntegrationBestSuggestedActionEntityLinkDataToJSON(value['linkData']),
    };
}

