/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields } from './EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields';
import {
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSONTyped,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSONTyped,
} from './EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields';

/**
 * 
 * @export
 * @interface EmailForwardingIntegrationBestSuggestedActionEntityLinkData
 */
export interface EmailForwardingIntegrationBestSuggestedActionEntityLinkData {
    /**
     * Id do lançamento financeiro a ser vinculado.
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityLinkData
     */
    financialRecordId: string;
    /**
     * 
     * @type {EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityLinkData
     */
    extractedFields: EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields;
}

/**
 * Check if a given object implements the EmailForwardingIntegrationBestSuggestedActionEntityLinkData interface.
 */
export function instanceOfEmailForwardingIntegrationBestSuggestedActionEntityLinkData(value: object): value is EmailForwardingIntegrationBestSuggestedActionEntityLinkData {
    if (!('financialRecordId' in value) || value['financialRecordId'] === undefined) return false;
    if (!('extractedFields' in value) || value['extractedFields'] === undefined) return false;
    return true;
}

export function EmailForwardingIntegrationBestSuggestedActionEntityLinkDataFromJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityLinkData {
    return EmailForwardingIntegrationBestSuggestedActionEntityLinkDataFromJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityLinkDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailForwardingIntegrationBestSuggestedActionEntityLinkData {
    if (json == null) {
        return json;
    }
    return {
        
        'financialRecordId': json['financialRecordId'],
        'extractedFields': EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSON(json['extractedFields']),
    };
}

export function EmailForwardingIntegrationBestSuggestedActionEntityLinkDataToJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityLinkData {
    return EmailForwardingIntegrationBestSuggestedActionEntityLinkDataToJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityLinkDataToJSONTyped(value?: EmailForwardingIntegrationBestSuggestedActionEntityLinkData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'financialRecordId': value['financialRecordId'],
        'extractedFields': EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSON(value['extractedFields']),
    };
}

