/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord } from './BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord';
import {
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordFromJSON,
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordFromJSONTyped,
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordToJSON,
    BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordToJSONTyped,
} from './BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord';

/**
 * 
 * @export
 * @interface EmailForwardingIntegrationBestSuggestedActionEntityCreateData
 */
export interface EmailForwardingIntegrationBestSuggestedActionEntityCreateData {
    /**
     * 
     * @type {BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityCreateData
     */
    financialRecord: BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecord;
}

/**
 * Check if a given object implements the EmailForwardingIntegrationBestSuggestedActionEntityCreateData interface.
 */
export function instanceOfEmailForwardingIntegrationBestSuggestedActionEntityCreateData(value: object): value is EmailForwardingIntegrationBestSuggestedActionEntityCreateData {
    if (!('financialRecord' in value) || value['financialRecord'] === undefined) return false;
    return true;
}

export function EmailForwardingIntegrationBestSuggestedActionEntityCreateDataFromJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityCreateData {
    return EmailForwardingIntegrationBestSuggestedActionEntityCreateDataFromJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailForwardingIntegrationBestSuggestedActionEntityCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'financialRecord': BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordFromJSON(json['financialRecord']),
    };
}

export function EmailForwardingIntegrationBestSuggestedActionEntityCreateDataToJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityCreateData {
    return EmailForwardingIntegrationBestSuggestedActionEntityCreateDataToJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityCreateDataToJSONTyped(value?: EmailForwardingIntegrationBestSuggestedActionEntityCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'financialRecord': BankTransactionsBestSuggestedActionEntityCreateDataFinancialRecordToJSON(value['financialRecord']),
    };
}

