/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields } from './EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields';
import {
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSONTyped,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSON,
    EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSONTyped,
} from './EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields';

/**
 * 
 * @export
 * @interface EmailForwardingIntegrationBestSuggestedActionEntityUpdateData
 */
export interface EmailForwardingIntegrationBestSuggestedActionEntityUpdateData {
    /**
     * Id do lançamento financeiro a ser atualizado.
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateData
     */
    id: string;
    /**
     * 
     * @type {EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateData
     */
    updateFields: EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields;
    /**
     * 
     * @type {EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateData
     */
    extractedFields: EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields;
}

/**
 * Check if a given object implements the EmailForwardingIntegrationBestSuggestedActionEntityUpdateData interface.
 */
export function instanceOfEmailForwardingIntegrationBestSuggestedActionEntityUpdateData(value: object): value is EmailForwardingIntegrationBestSuggestedActionEntityUpdateData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updateFields' in value) || value['updateFields'] === undefined) return false;
    if (!('extractedFields' in value) || value['extractedFields'] === undefined) return false;
    return true;
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataFromJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityUpdateData {
    return EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataFromJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailForwardingIntegrationBestSuggestedActionEntityUpdateData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'updateFields': EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSON(json['updateFields']),
        'extractedFields': EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSON(json['extractedFields']),
    };
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataToJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityUpdateData {
    return EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataToJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataToJSONTyped(value?: EmailForwardingIntegrationBestSuggestedActionEntityUpdateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'updateFields': EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSON(value['updateFields']),
        'extractedFields': EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSON(value['extractedFields']),
    };
}

