/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
 */
export interface EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields {
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    direction?: EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    dueDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    contact?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    subcategory?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    account?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    concluded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    cashDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    discount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    finesAndInterests?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    boletoCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    pixCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields
     */
    pixKey?: string | null;
}


/**
 * @export
 */
export const EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsDirectionEnum = typeof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsDirectionEnum[keyof typeof EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsDirectionEnum];


/**
 * Check if a given object implements the EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields interface.
 */
export function instanceOfEmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields(value: object): value is EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields {
    return true;
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields {
    return EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields {
    if (json == null) {
        return json;
    }
    return {
        
        'direction': json['direction'] == null ? undefined : json['direction'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'dueDate': json['dueDate'] == null ? undefined : json['dueDate'],
        'description': json['description'] == null ? undefined : json['description'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'account': json['account'] == null ? undefined : json['account'],
        'concluded': json['concluded'] == null ? undefined : json['concluded'],
        'cashDate': json['cashDate'] == null ? undefined : json['cashDate'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'finesAndInterests': json['finesAndInterests'] == null ? undefined : json['finesAndInterests'],
        'boletoCode': json['boletoCode'] == null ? undefined : json['boletoCode'],
        'pixCode': json['pixCode'] == null ? undefined : json['pixCode'],
        'pixKey': json['pixKey'] == null ? undefined : json['pixKey'],
    };
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSON(json: any): EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields {
    return EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSONTyped(json, false);
}

export function EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFieldsToJSONTyped(value?: EmailForwardingIntegrationBestSuggestedActionEntityUpdateDataUpdateFields | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'direction': value['direction'],
        'amount': value['amount'],
        'dueDate': value['dueDate'],
        'description': value['description'],
        'contact': value['contact'],
        'subcategory': value['subcategory'],
        'account': value['account'],
        'concluded': value['concluded'],
        'cashDate': value['cashDate'],
        'discount': value['discount'],
        'finesAndInterests': value['finesAndInterests'],
        'boletoCode': value['boletoCode'],
        'pixCode': value['pixCode'],
        'pixKey': value['pixKey'],
    };
}

