/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 4.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartBulkCreateExtractionForWebAppRequestBodyDtoFile } from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import {
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped,
} from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';

/**
 * 
 * @export
 * @interface ExtractFinancialRecordFromFileRequestBodyDto
 */
export interface ExtractFinancialRecordFromFileRequestBodyDto {
    /**
     * 
     * @type {StartBulkCreateExtractionForWebAppRequestBodyDtoFile}
     * @memberof ExtractFinancialRecordFromFileRequestBodyDto
     */
    file: StartBulkCreateExtractionForWebAppRequestBodyDtoFile;
}

/**
 * Check if a given object implements the ExtractFinancialRecordFromFileRequestBodyDto interface.
 */
export function instanceOfExtractFinancialRecordFromFileRequestBodyDto(value: object): value is ExtractFinancialRecordFromFileRequestBodyDto {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function ExtractFinancialRecordFromFileRequestBodyDtoFromJSON(json: any): ExtractFinancialRecordFromFileRequestBodyDto {
    return ExtractFinancialRecordFromFileRequestBodyDtoFromJSONTyped(json, false);
}

export function ExtractFinancialRecordFromFileRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractFinancialRecordFromFileRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON(json['file']),
    };
}

export function ExtractFinancialRecordFromFileRequestBodyDtoToJSON(json: any): ExtractFinancialRecordFromFileRequestBodyDto {
    return ExtractFinancialRecordFromFileRequestBodyDtoToJSONTyped(json, false);
}

export function ExtractFinancialRecordFromFileRequestBodyDtoToJSONTyped(value?: ExtractFinancialRecordFromFileRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON(value['file']),
    };
}

