/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartBulkCreateExtractionForWebAppRequestBodyDtoFile } from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import {
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped,
} from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';

/**
 * 
 * @export
 * @interface ExtractContactFromFileRequestBodyDto
 */
export interface ExtractContactFromFileRequestBodyDto {
    /**
     * 
     * @type {StartBulkCreateExtractionForWebAppRequestBodyDtoFile}
     * @memberof ExtractContactFromFileRequestBodyDto
     */
    file: StartBulkCreateExtractionForWebAppRequestBodyDtoFile;
}

/**
 * Check if a given object implements the ExtractContactFromFileRequestBodyDto interface.
 */
export function instanceOfExtractContactFromFileRequestBodyDto(value: object): value is ExtractContactFromFileRequestBodyDto {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function ExtractContactFromFileRequestBodyDtoFromJSON(json: any): ExtractContactFromFileRequestBodyDto {
    return ExtractContactFromFileRequestBodyDtoFromJSONTyped(json, false);
}

export function ExtractContactFromFileRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractContactFromFileRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON(json['file']),
    };
}

export function ExtractContactFromFileRequestBodyDtoToJSON(json: any): ExtractContactFromFileRequestBodyDto {
    return ExtractContactFromFileRequestBodyDtoToJSONTyped(json, false);
}

export function ExtractContactFromFileRequestBodyDtoToJSONTyped(value?: ExtractContactFromFileRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON(value['file']),
    };
}

