/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom } from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom';
import {
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSONTyped,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSONTyped,
} from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom';
import type { GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted } from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted';
import {
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedFromJSONTyped,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedToJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedToJSONTyped,
} from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted';
import type { GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner } from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner';
import {
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSONTyped,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSONTyped,
} from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner';

/**
 * 
 * @export
 * @interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage
 */
export interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage {
    /**
     * ID da mensagem.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage
     */
    id: string;
    /**
     * 
     * @type {GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage
     */
    from: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom;
    /**
     * Timestamp da mensagem.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage
     */
    timestamp: string;
    /**
     * Conteúdo da mensagem.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage
     */
    content: string;
    /**
     * Arquivos da mensagem.
     * @type {Array<GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner>}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage
     */
    files: Array<GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner>;
    /**
     * 
     * @type {GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage
     */
    quoted?: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted | null;
}

/**
 * Check if a given object implements the GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage interface.
 */
export function instanceOfGenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage(value: object): value is GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'from': GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSON(json['from']),
        'timestamp': json['timestamp'],
        'content': json['content'],
        'files': ((json['files'] as Array<any>).map(GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSON)),
        'quoted': json['quoted'] == null ? undefined : GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedFromJSON(json['quoted']),
    };
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToJSONTyped(value?: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'from': GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSON(value['from']),
        'timestamp': value['timestamp'],
        'content': value['content'],
        'files': ((value['files'] as Array<any>).map(GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSON)),
        'quoted': GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedToJSON(value['quoted']),
    };
}

