/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 2.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner
 */
export interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner {
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner
     */
    toolCallId: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner
     */
    toolName: string;
    /**
     * 
     * @type {any}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner
     */
    input: any | null;
}

/**
 * Check if a given object implements the GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner interface.
 */
export function instanceOfGenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner(value: object): value is GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner {
    if (!('toolCallId' in value) || value['toolCallId'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInnerFromJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInnerFromJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'toolCallId': json['toolCallId'],
        'toolName': json['toolName'],
        'input': json['input'],
    };
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInnerToJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInnerToJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInnerToJSONTyped(value?: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToolCallsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toolCallId': value['toolCallId'],
        'toolName': value['toolName'],
        'input': value['input'],
    };
}

