/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo
 */
export interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo {
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo interface.
 */
export function instanceOfGenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo(value: object): value is GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo {
    return true;
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToFromJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToFromJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToToJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToToJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageToToJSONTyped(value?: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageTo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phone': value['phone'],
    };
}

