/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenerateBestSuggestedActionRequestBodyDtoMessageContext } from './GenerateBestSuggestedActionRequestBodyDtoMessageContext';
import {
    GenerateBestSuggestedActionRequestBodyDtoMessageContextFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextFromJSONTyped,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextToJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextToJSONTyped,
} from './GenerateBestSuggestedActionRequestBodyDtoMessageContext';
import type { StartBulkCreateExtractionForWebAppRequestBodyDtoFile } from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import {
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped,
} from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';

/**
 * 
 * @export
 * @interface GenerateBestSuggestedActionRequestBodyDto
 */
export interface GenerateBestSuggestedActionRequestBodyDto {
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDto
     */
    organizationId: string;
    /**
     * 
     * @type {Array<StartBulkCreateExtractionForWebAppRequestBodyDtoFile>}
     * @memberof GenerateBestSuggestedActionRequestBodyDto
     */
    files: Array<StartBulkCreateExtractionForWebAppRequestBodyDtoFile>;
    /**
     * 
     * @type {GenerateBestSuggestedActionRequestBodyDtoMessageContext}
     * @memberof GenerateBestSuggestedActionRequestBodyDto
     */
    messageContext?: GenerateBestSuggestedActionRequestBodyDtoMessageContext | null;
}

/**
 * Check if a given object implements the GenerateBestSuggestedActionRequestBodyDto interface.
 */
export function instanceOfGenerateBestSuggestedActionRequestBodyDto(value: object): value is GenerateBestSuggestedActionRequestBodyDto {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function GenerateBestSuggestedActionRequestBodyDtoFromJSON(json: any): GenerateBestSuggestedActionRequestBodyDto {
    return GenerateBestSuggestedActionRequestBodyDtoFromJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBestSuggestedActionRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'],
        'files': ((json['files'] as Array<any>).map(StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON)),
        'messageContext': json['messageContext'] == null ? undefined : GenerateBestSuggestedActionRequestBodyDtoMessageContextFromJSON(json['messageContext']),
    };
}

export function GenerateBestSuggestedActionRequestBodyDtoToJSON(json: any): GenerateBestSuggestedActionRequestBodyDto {
    return GenerateBestSuggestedActionRequestBodyDtoToJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoToJSONTyped(value?: GenerateBestSuggestedActionRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
        'files': ((value['files'] as Array<any>).map(StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON)),
        'messageContext': GenerateBestSuggestedActionRequestBodyDtoMessageContextToJSON(value['messageContext']),
    };
}

