/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 3.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner
 */
export interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner {
    /**
     * Nome do arquivo.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner
     */
    name: string;
    /**
     * URL do arquivo.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner
     */
    url: string;
    /**
     * Tipo MIME do arquivo.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner
     */
    mimeType: string;
}

/**
 * Check if a given object implements the GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner interface.
 */
export function instanceOfGenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner(value: object): value is GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'mimeType': json['mimeType'],
    };
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSONTyped(value?: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'mimeType': value['mimeType'],
    };
}

