/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.8.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom
 */
export interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom {
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom interface.
 */
export function instanceOfGenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom(value: object): value is GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom {
    return true;
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSONTyped(value?: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
    };
}

