/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.8.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom } from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom';
import {
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSONTyped,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSONTyped,
} from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom';
import type { GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner } from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner';
import {
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSONTyped,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSON,
    GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSONTyped,
} from './GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner';

/**
 * 
 * @export
 * @interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted
 */
export interface GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted {
    /**
     * ID da mensagem citada.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted
     */
    id: string;
    /**
     * Timestamp da mensagem citada.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted
     */
    timestamp: string;
    /**
     * 
     * @type {GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted
     */
    from: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFrom;
    /**
     * Conteúdo da mensagem citada.
     * @type {string}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted
     */
    content: string;
    /**
     * Arquivos da mensagem citada.
     * @type {Array<GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner>}
     * @memberof GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted
     */
    files: Array<GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInner>;
}

/**
 * Check if a given object implements the GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted interface.
 */
export function instanceOfGenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted(value: object): value is GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedFromJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedFromJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'from': GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromFromJSON(json['from']),
        'content': json['content'],
        'files': ((json['files'] as Array<any>).map(GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerFromJSON)),
    };
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedToJSON(json: any): GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted {
    return GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedToJSONTyped(json, false);
}

export function GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuotedToJSONTyped(value?: GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageQuoted | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'],
        'from': GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFromToJSON(value['from']),
        'content': value['content'],
        'files': ((value['files'] as Array<any>).map(GenerateBestSuggestedActionRequestBodyDtoMessageContextCurrentMessageFilesInnerToJSON)),
    };
}

