/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.8.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobRequestPayloadEntity
 */
export interface JobRequestPayloadEntity {
    /**
     * 
     * @type {string}
     * @memberof JobRequestPayloadEntity
     */
    jobRequestId: string;
}

/**
 * Check if a given object implements the JobRequestPayloadEntity interface.
 */
export function instanceOfJobRequestPayloadEntity(value: object): value is JobRequestPayloadEntity {
    if (!('jobRequestId' in value) || value['jobRequestId'] === undefined) return false;
    return true;
}

export function JobRequestPayloadEntityFromJSON(json: any): JobRequestPayloadEntity {
    return JobRequestPayloadEntityFromJSONTyped(json, false);
}

export function JobRequestPayloadEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobRequestPayloadEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'jobRequestId': json['jobRequestId'],
    };
}

export function JobRequestPayloadEntityToJSON(json: any): JobRequestPayloadEntity {
    return JobRequestPayloadEntityToJSONTyped(json, false);
}

export function JobRequestPayloadEntityToJSONTyped(value?: JobRequestPayloadEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobRequestId': value['jobRequestId'],
    };
}

