/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartBulkCreateExtractionForWebAppRequestBodyDtoFile } from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';
import {
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON,
    StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped,
} from './StartBulkCreateExtractionForWebAppRequestBodyDtoFile';

/**
 * 
 * @export
 * @interface StartBulkCreateExtractionForWebAppRequestBodyDto
 */
export interface StartBulkCreateExtractionForWebAppRequestBodyDto {
    /**
     * 
     * @type {StartBulkCreateExtractionForWebAppRequestBodyDtoFile}
     * @memberof StartBulkCreateExtractionForWebAppRequestBodyDto
     */
    file: StartBulkCreateExtractionForWebAppRequestBodyDtoFile;
}

/**
 * Check if a given object implements the StartBulkCreateExtractionForWebAppRequestBodyDto interface.
 */
export function instanceOfStartBulkCreateExtractionForWebAppRequestBodyDto(value: object): value is StartBulkCreateExtractionForWebAppRequestBodyDto {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoFromJSON(json: any): StartBulkCreateExtractionForWebAppRequestBodyDto {
    return StartBulkCreateExtractionForWebAppRequestBodyDtoFromJSONTyped(json, false);
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartBulkCreateExtractionForWebAppRequestBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON(json['file']),
    };
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoToJSON(json: any): StartBulkCreateExtractionForWebAppRequestBodyDto {
    return StartBulkCreateExtractionForWebAppRequestBodyDtoToJSONTyped(json, false);
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoToJSONTyped(value?: StartBulkCreateExtractionForWebAppRequestBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON(value['file']),
    };
}

