/* tslint:disable */
/* eslint-disable */
/**
 * Sofia Pegasus ai-api
 * Api do sistema Pegasus com endpoints para interação com os modelos de AI usados no sistema.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartBulkCreateExtractionForWebAppRequestBodyDtoFile
 */
export interface StartBulkCreateExtractionForWebAppRequestBodyDtoFile {
    /**
     * 
     * @type {string}
     * @memberof StartBulkCreateExtractionForWebAppRequestBodyDtoFile
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof StartBulkCreateExtractionForWebAppRequestBodyDtoFile
     */
    signedUrl: string;
    /**
     * 
     * @type {string}
     * @memberof StartBulkCreateExtractionForWebAppRequestBodyDtoFile
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof StartBulkCreateExtractionForWebAppRequestBodyDtoFile
     */
    fileName: string;
}

/**
 * Check if a given object implements the StartBulkCreateExtractionForWebAppRequestBodyDtoFile interface.
 */
export function instanceOfStartBulkCreateExtractionForWebAppRequestBodyDtoFile(value: object): value is StartBulkCreateExtractionForWebAppRequestBodyDtoFile {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('signedUrl' in value) || value['signedUrl'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSON(json: any): StartBulkCreateExtractionForWebAppRequestBodyDtoFile {
    return StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped(json, false);
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartBulkCreateExtractionForWebAppRequestBodyDtoFile {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'signedUrl': json['signedUrl'],
        'mimeType': json['mimeType'],
        'fileName': json['fileName'],
    };
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSON(json: any): StartBulkCreateExtractionForWebAppRequestBodyDtoFile {
    return StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped(json, false);
}

export function StartBulkCreateExtractionForWebAppRequestBodyDtoFileToJSONTyped(value?: StartBulkCreateExtractionForWebAppRequestBodyDtoFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'signedUrl': value['signedUrl'],
        'mimeType': value['mimeType'],
        'fileName': value['fileName'],
    };
}

